name: hailo
description: A new Flutter project.
version: 1.0.4+5
environment: 
  sdk: '>=2.18.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter

  get: ^4.6.5
  cupertino_icons: ^1.0.2
  get_storage: ^2.0.3
  http:
  cached_network_image: ^3.2.1
  image_picker: ^0.8.6
  scroll_date_picker: ^3.6.0
  intl: ^0.17.0
  smooth_page_indicator: ^1.0.0+2
  fl_country_code_picker: ^0.0.3+1
  pinput: any
#  pinput: ^2.2.31
  fluttertoast: ^8.1.1
  auto_size_text: ^3.0.0
  table_calendar: ^3.0.7
  google_maps_flutter: ^2.2.1
  geolocator: ^9.0.2
  geocoding: ^2.0.4
  rating_dialog: ^2.0.4
  dropdown_button2: ^1.8.5
  custom_map_markers: ^0.0.2+1
  google_maps_widget: ^1.0.5+1
  cloud_functions: ^3.3.8
  flutter_stripe: ^7.0.0
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.2
  cloud_firestore: ^3.5.1
  firebase_messaging: ^13.1.0
  firebase_storage: ^10.3.11
  firebase_app_check: ^0.0.9+1
  readmore: ^2.2.0
  sizer:
  paginate_firestore: ^1.0.3+1
  lazy_load_scrollview: ^1.3.0
  remixicon: ^1.0.0
  lottie: ^1.4.3
  multiselect: ^0.0.7
  flutter_calendar_carousel: ^2.4.0
  flutter_rating_bar: ^4.0.1
  multi_select_flutter: ^4.1.3
  weekday_selector: ^1.1.0
  flutter_datetime_picker:





dev_dependencies: 
  flutter_test: 
    sdk: flutter

  flutter_lints: ^2.0.0

flutter: 
  uses-material-design: true
  assets: 
    - assets/

  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
